name: jacov
description: JSON converters for package:jacov.
version: 0.1.7
repository: https://github.com/asbloom-py/Jacov.git

environment:
  sdk: '>=3.4.0 <4.0.0'
  flutter: '>=3.22.0'

dependencies:
  cloud_firestore: ^5.1.0
  freezed_annotation: ^2.4.4
  google_maps_flutter: ^2.7.0
  json_annotation: ^4.9.0

dev_dependencies:
  build_runner: null
  fake_cloud_firestore: null
  flutter_test:
    sdk: flutter
  freezed: null
  json_serializable: null
  pedantic_mono: null
  test: null
